//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DayZLauncher {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.7.0.0")]
    internal sealed partial class LauncherSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static LauncherSettings defaultInstance = ((LauncherSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new LauncherSettings())));
        
        public static LauncherSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GamePath {
            get {
                return ((string)(this["GamePath"]));
            }
            set {
                this["GamePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool High {
            get {
                return ((bool)(this["High"]));
            }
            set {
                this["High"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool StartMemreduct {
            get {
                return ((bool)(this["StartMemreduct"]));
            }
            set {
                this["StartMemreduct"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DisableWindowsEffects {
            get {
                return ((bool)(this["DisableWindowsEffects"]));
            }
            set {
                this["DisableWindowsEffects"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CloseSteam {
            get {
                return ((bool)(this["CloseSteam"]));
            }
            set {
                this["CloseSteam"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Survivor")]
        public string ProfileName {
            get {
                return ((string)(this["ProfileName"]));
            }
            set {
                this["ProfileName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MemMax {
            get {
                return ((string)(this["MemMax"]));
            }
            set {
                this["MemMax"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MaxVRam {
            get {
                return ((string)(this["MaxVRam"]));
            }
            set {
                this["MaxVRam"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CpuCount {
            get {
                return ((string)(this["CpuCount"]));
            }
            set {
                this["CpuCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ExThreads {
            get {
                return ((string)(this["ExThreads"]));
            }
            set {
                this["ExThreads"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SceneComplexity {
            get {
                return ((string)(this["SceneComplexity"]));
            }
            set {
                this["SceneComplexity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ShadowZDistance {
            get {
                return ((string)(this["ShadowZDistance"]));
            }
            set {
                this["ShadowZDistance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ViewDistance {
            get {
                return ((string)(this["ViewDistance"]));
            }
            set {
                this["ViewDistance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PreferredObjectViewDistance {
            get {
                return ((string)(this["PreferredObjectViewDistance"]));
            }
            set {
                this["PreferredObjectViewDistance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TerrainGrid {
            get {
                return ((string)(this["TerrainGrid"]));
            }
            set {
                this["TerrainGrid"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"version=1;
blood=1;
singleVoice=0;
gamma=1;
battleyeLicense=1;
lastMPServer=""5.188.158.148:150863872"";
lastMPServerName=""GGAMES DayZ 1.08 Moded | Autumn server 1"";
lastMPMission=""ChernarusPlusGloom"";
inputVersion=1;
perspective=1;
trackIR=1;
freeTrack=1;
mouseSmoothing=30;
maxSamplesPlayed=32;
TexQuality=4;
tripleHead=0;
showTitles=1;
vehicleFreelook=0;
shadowQuality=2;
mouseSensitivityX=1;
mouseSensitivityY=1;
controllerSensitivityX=1;
controllerSensitivityY=1;
volumeMaster=10;
volumeCD=0;
volumeFX=5;
volumeSpeech=5;
volumeVoN=10;
vonRecThreshold=0.029999999;
brightness=1;
uiTopLeftX=0.12500001;
uiTopLeftY=0;
uiBottomRightX=0.875;
uiBottomRightY=1;
IGUIScale=0.55000001;
headBob=1;
sceneComplexity=750000;
shadowZDistance=175;
viewDistance=2200;
preferredObjectViewDistance=1375.8242;
terrainGrid=3.125;
fov=0.95993;")]
        public string DayZSettings {
            get {
                return ((string)(this["DayZSettings"]));
            }
            set {
                this["DayZSettings"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"[Launcher]
Target = DayZ_BE.exe
StartIn = 
CommandLine = -name=Survivor ""-mod=;"" -nosplash -skipIntro -noPause -nologs -cpuCount=4 -exThreads=0 -maxMem=4096 -maxVRAM=2048 -ReplLastServToWritedPar -HideOption  -HideChooseServer -HideCharacterStats -HideNewsFeed -connect=127.0.0.1 -port=2302
SteamClientPath = SmartSteamEmu\SmartSteamEmu.dll
SteamClientPath64 = SmartSteamEmu\SmartSteamEmu64.dll
Persist = 0
ParanoidMode = 0
InjectDll = 0

[SmartSteamEmu]
AvatarFilename = avatar.png
PersonaName = Tester
AppId = 221100
SteamIdGeneration = GenerateRandom
Language = English

VR = False
Offline = False
QuickJoinHotkey = SHIFT + TAB
MasterServer = 188.40.40.201:27010
MasterServerGoldSrc = 188.40.40.201:27010
[Achievements]
FailOnNonExistenceStats = False

[SSEOverlay]
DisableOverlay = True
OnlineMode = True
Language = 
ScreenshotHotkey = F12
HookRefCount = True
OnlineKey = 

[DirectPatch]

[Debug]
EnableLog = False
MarkLogHotkey = CTRL + ALT + M
LogFilter = User Logged On
Minidump = False

[DLC]
Default = True

[Networking]
BroadcastAddress = 192.168.0.1
ListenPort = 31313
MaximumPort = 10
DiscoveryInterval = 3
MaximumConnection = 200

[PlayerManagement]
AllowAnyoneConnect = False
AdminPassword = ")]
        public string StartIni {
            get {
                return ((string)(this["StartIni"]));
            }
            set {
                this["StartIni"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("start \"\" \"SmartSteamEmu\\SmartSteamLoader.exe\" !StartGame.ini\r\nexit")]
        public string StartGameBat {
            get {
                return ((string)(this["StartGameBat"]));
            }
            set {
                this["StartGameBat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"mod\@CommunityFramework;mod\@CommunityOnlineTools;mod\@DayZExpansion;mod\@DayZExpansionLicensed;mod\@ToxicZone;mod\@Banking;mod\@BetterInspect;mod\@BountyFix;mod\@Builderitems;mod\@DboSlots;mod\@Fliptransport;mod\@Plus200Home;mod\@SnapHeliToHelipad;mod\@zspawnselection;mod\@Zspawnselbaseadd;mod\@AdvancedWeaponScopes;mod\@Awesomearmbands;mod\@Camonetplusv1041;mod\@ChernarusrpAe86;mod\@Cj187cars;mod\@Cl0udsMilitaryGear;mod\@CmzSupercar;mod\@CrskBmw525iE34;mod\@Crskvaz2107;mod\@CustomBarrelsByKaetzchen;mod\@DayzNavigation;mod\@DingoTruck;mod\@FidovPack4;mod\@InvisibleClothingMod;mod\@KamazTruck;mod\@LandRoverDefender110;mod\@MassSmanyitemoverhaul;mod\@MercedesG65amg;mod\@ModularVestSystem;mod\@Moreguns;mod\@Muchstuffpack;mod\@NehrPickupLadaExpansion;mod\@AltarCommandoUnitBlackmarketTrader;mod\@ChernarusBattalionHeadquartersSkalistyIsland;mod\@NeafAircraftMilitaryBase;mod\@PavlovoMediumSecurityMilitary;mod\@PrisionIslandSuperMaxCorrectionalFacility;mod\@108clothingfixedz;mod\@modconflictfix;mod\@noexplodinghelis;mod\@UnofficialExpansionFixes;mod\@Trader;mod\@TraderFixesandFeatures;mod\@Lightsword")]
        public string Mods {
            get {
                return ((string)(this["Mods"]));
            }
            set {
                this["Mods"] = value;
            }
        }
    }
}
