//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DayZLauncher {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.6.0.0")]
    internal sealed partial class LauncherSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static LauncherSettings defaultInstance = ((LauncherSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new LauncherSettings())));
        
        public static LauncherSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GamePath {
            get {
                return ((string)(this["GamePath"]));
            }
            set {
                this["GamePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool High {
            get {
                return ((bool)(this["High"]));
            }
            set {
                this["High"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool StartMemreduct {
            get {
                return ((bool)(this["StartMemreduct"]));
            }
            set {
                this["StartMemreduct"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DisableWindowsEffects {
            get {
                return ((bool)(this["DisableWindowsEffects"]));
            }
            set {
                this["DisableWindowsEffects"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CloseSteam {
            get {
                return ((bool)(this["CloseSteam"]));
            }
            set {
                this["CloseSteam"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Survivor")]
        public string ProfileName {
            get {
                return ((string)(this["ProfileName"]));
            }
            set {
                this["ProfileName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MemMax {
            get {
                return ((string)(this["MemMax"]));
            }
            set {
                this["MemMax"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MaxVRam {
            get {
                return ((string)(this["MaxVRam"]));
            }
            set {
                this["MaxVRam"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CpuCount {
            get {
                return ((string)(this["CpuCount"]));
            }
            set {
                this["CpuCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ExThreads {
            get {
                return ((string)(this["ExThreads"]));
            }
            set {
                this["ExThreads"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SceneComplexity {
            get {
                return ((string)(this["SceneComplexity"]));
            }
            set {
                this["SceneComplexity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ShadowZDistance {
            get {
                return ((string)(this["ShadowZDistance"]));
            }
            set {
                this["ShadowZDistance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ViewDistance {
            get {
                return ((string)(this["ViewDistance"]));
            }
            set {
                this["ViewDistance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PreferredObjectViewDistance {
            get {
                return ((string)(this["PreferredObjectViewDistance"]));
            }
            set {
                this["PreferredObjectViewDistance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TerrainGrid {
            get {
                return ((string)(this["TerrainGrid"]));
            }
            set {
                this["TerrainGrid"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"version=1;
blood=1;
singleVoice=0;
gamma=1;
battleyeLicense=1;
lastMPServer=""5.188.158.148:150863872"";
lastMPServerName=""GGAMES DayZ 1.08 Moded | Autumn server 1"";
lastMPMission=""ChernarusPlusGloom"";
inputVersion=1;
perspective=1;
trackIR=1;
freeTrack=1;
mouseSmoothing=30;
maxSamplesPlayed=32;
TexQuality=4;
tripleHead=0;
showTitles=1;
vehicleFreelook=0;
shadowQuality=2;
mouseSensitivityX=1;
mouseSensitivityY=1;
controllerSensitivityX=1;
controllerSensitivityY=1;
volumeMaster=10;
volumeCD=0;
volumeFX=5;
volumeSpeech=5;
volumeVoN=10;
vonRecThreshold=0.029999999;
brightness=1;
uiTopLeftX=0.12500001;
uiTopLeftY=0;
uiBottomRightX=0.875;
uiBottomRightY=1;
IGUIScale=0.55000001;
headBob=1;
sceneComplexity=750000;
shadowZDistance=175;
viewDistance=2200;
preferredObjectViewDistance=1375.8242;
terrainGrid=3.125;
fov=0.95993;")]
        public string DayZSettings {
            get {
                return ((string)(this["DayZSettings"]));
            }
            set {
                this["DayZSettings"] = value;
            }
        }
    }
}
